import { z } from "zod";

/**
 * Shared building blocks for every section schema.
 *
 * Rule of thumb used throughout: the AI only ever produces `content` + `variant`.
 * Anything visual/deterministic (accent colour, seed, shape count, motion timing)
 * is computed by the app and lives in `style`, so a model can never break layout.
 */

/** Lives here rather than in section.ts so brief.ts can use it without a circular import. */
export const SECTION_TYPES = ["hero", "features", "testimonials", "cta"] as const;
export const SectionType = z.enum(SECTION_TYPES);
export type SectionType = z.infer<typeof SectionType>;

export const hexColor = z
  .string()
  .regex(/^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/, "Expected a hex colour, e.g. #1B4D3E");

/** Trimmed, non-empty, length-capped string. Caps are layout constraints, not style preferences. */
export const text = (max: number) => z.string().trim().min(1).max(max);

/* ---------------------------------------------------------------- images */

/**
 * The model picks a CATEGORY, never a filename. The app then resolves the
 * category to a concrete file from the curated set using the project seed.
 * This makes hallucinated image paths structurally impossible.
 */
export const IMAGE_CATEGORIES = [
  "people-team",
  "people-portrait",
  "workspace",
  "product-object",
  "food-drink",
  "nature",
  "architecture",
  "texture-abstract",
  "tools-craft",
  "screens-tech",
] as const;

export const CuratedImage = z.object({
  category: z.enum(IMAGE_CATEGORIES),
  alt: text(120),
});
export type CuratedImage = z.infer<typeof CuratedImage>;

/* ----------------------------------------------------------------- icons */

/** Curated lucide-react subset. Closed enum = no hallucinated icon names. */
export const ICON_NAMES = [
  "sparkles", "zap", "shield", "heart", "leaf", "clock", "compass", "layers",
  "message-circle", "users", "trending-up", "package", "wand", "lock",
  "globe", "phone", "calendar", "star", "check", "gauge", "palette",
  "truck", "coffee", "scissors",
] as const;

export const IconName = z.enum(ICON_NAMES);
export type IconName = z.infer<typeof IconName>;

/* ------------------------------------------------------------------ ctas */

export const CtaLink = z.object({
  label: text(28),
  /** No real destinations exist in preview-only scope; kept so the contract survives if that changes. */
  href: z.string().default("#"),
});
export type CtaLink = z.infer<typeof CtaLink>;

/* ----------------------------------------------------------------- style */

export const MotionIntensity = z.enum(["subtle", "balanced", "lively"]);

/** App-owned. Never generated by the model, never edited by a targeted edit. */
export const SectionStyle = z.object({
  accent: hexColor,
  accentAlt: hexColor,
  /** Per-section seed derived from projectId + sectionId. Drives shape positions and timing jitter. */
  seed: z.number().int().nonnegative(),
  motion: MotionIntensity.default("balanced"),
  floatingShapes: z.number().int().min(0).max(6).default(3),
  cursorGlow: z.boolean().default(true),
});
export type SectionStyle = z.infer<typeof SectionStyle>;

/**
 * No "failed" state: the fallback path always produces something renderable.
 * Failures are recorded on GenerationAttempt instead, so the log stays honest
 * while the preview stays intact.
 */
export const SectionStatus = z.enum(["pending", "generating", "valid", "fallback"]);
export type SectionStatus = z.infer<typeof SectionStatus>;

/* --------------------------------------------------- variant slot checks */

/**
 * Some variants need slots the base content schema marks optional
 * (split layouts need an image, an orbital hero needs proof points).
 * Applied at the generation boundary only — see the note in section.ts about
 * why the stored section schemas stay refinement-free.
 */
export function requireSlots<V extends string, C extends Record<string, unknown>>(
  requirements: Record<V, readonly (keyof C & string)[]>,
) {
  return (value: { variant: V; content: C }, ctx: z.RefinementCtx) => {
    for (const slot of requirements[value.variant] ?? []) {
      const v = value.content[slot];
      if (v === undefined || v === null || (Array.isArray(v) && v.length === 0)) {
        ctx.addIssue({
          code: "custom",
          path: ["content", slot],
          message: `The "${value.variant}" layout needs "${slot}" to be filled in.`,
        });
      }
    }
  };
}

/** Same idea for variants that only work at a specific item count. */
export function requireItemCount<V extends string>(
  ranges: Record<V, readonly [number, number]>,
) {
  return (value: { variant: V; content: { items: unknown[] } }, ctx: z.RefinementCtx) => {
    const range = ranges[value.variant];
    if (!range) return;
    const [min, max] = range;
    const n = value.content.items.length;
    if (n < min || n > max) {
      ctx.addIssue({
        code: "custom",
        path: ["content", "items"],
        message: `The "${value.variant}" layout needs between ${min} and ${max} items, got ${n}.`,
      });
    }
  };
}
